apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containters:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
  